### PR TITLE
Set up the build scripts

### PR DESCRIPTION
**Pull request by zsxwing**
Most of scripts are copied from Spark Avro and made necessary changes for this project.

### CODE REVIEW

**Comment by zsxwing** [comment]
cc @marmbrus could you take a look at the build scripts? How to test the publish process?

**Comment by marmbrus** [comment]
Looks pretty good.  Easiest way to test is probably to publish a 0.1 release

**Comment by zsxwing** [comment]
@marmbrus Thanks, I'm merging it now

**Comment by marmbrus** [comment]
We should probably copy the merge script too :)

**Comment by zsxwing** [comment]
It's in this PR :)

**Pull request merged**
